name: Publish updated templates to Microsoft systems

on:
  push:
  repository_dispatch:
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify internal systems to use updated templates
        run: |
          curl -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: token ${PAT}" \
            --request POST \
            --data '{"event_type": "rebuild-microsoft-oss-templates", "repository": "$GITHUB_REPOSITORY"}' \
            https://api.github.com/repos/${{ secrets.REPO_TEMPLATES_OSS_WORKFLOW_DISPATCH }}/dispatches
